config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gardens, only: [:index, :show] do
    resources :plants, only: [:create]
  end
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  validates :name, presence: true
  validates :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def index
    @gardens = Garden.all
  end

  def show
    @plant = Plant.new
    @garden = Garden.find(params[:id])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render "gardens/show"
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @garden = @plant.garden
    @plant.destroy
    redirect_to garden_path(@garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<h1>Gardens#index</h1>
<p>Find me in app/views/gardens/index.html.erb</p>

<ul>
  <% @gardens.each do |garden| %>
    <li><%= link_to garden.name, garden_path(garden) %></li>
  <% end %>
</ul>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
    <p><%= @garden.address %></p>
  </div>
</div>

<div class="cards mt-4">
  <% @garden.plants.each do |plant| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
      <%= plant.name %>
      <%= link_to "+",  plant_path(plant), method: :delete, data: { confirm: 'Are you sure ??' }, class: "card-remove-link" %>
    </div>
  <% end %>
</div>


<div class="container my-5">
  <div class="row">
    <div class="col-4 mx-auto">
      <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :image_url %>
      <%= f.input :alive %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>


<%= link_to 'Back', gardens_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>